name: Check Release

permissions:
  contents: write
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  check-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check if there is a new release
      id: latest_version
      run: |
        LATEST_VERSION=$(curl --silent "https://api.github.com/repos/wasmerio/wasmer/releases/latest" | jq -r .tag_name)
        echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT
        if git tag | grep -q "$LATEST_VERSION$"; then
          echo "We have already released this version. Exiting..."
          echo "new_release=false" >> $GITHUB_OUTPUT
        else
          echo "new_release=true" >> $GITHUB_OUTPUT
        fi

    - name: Fetch wasmer source code
      if: steps.latest_version.outputs.new_release == 'true'
      run: |
        git clone https://github.com/wasmerio/wasmer.git wasmer-sources

    - name: Install Rust
      if: steps.latest_version.outputs.new_release == 'true'
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y

    - name: Generate CAPI
      if: steps.latest_version.outputs.new_release == 'true'
      run: |
        cd wasmer-sources
        make build-capi
        make package-capi

    - name: Upload headers
      if: steps.latest_version.outputs.new_release == 'true'
      uses: ncipollo/release-action@v1
      with:
        artifacts: "wasmer-sources/package/include/*.h"
        commit: ${{ github.sha }}
        tag: ${{ steps.latest_version.outputs.version }}
        skipIfReleaseExists: true
